Repository X-TRON404/MyPal-dev, pull requests merged in 2021-10, with the labels that each got.

#7 style: confesssion section comments
  client/.eslintcache
  client/src/components/Confessions.css
  client/src/components/Confessions.js
Labels: Hacktoberfest

#12 docs: Add contributing guidelines to the project
  CONTRIBUTING.md
Labels: good first issue, Hacktoberfest

#11 docs: Add code of conduct to the project
  CODE_OF_CONDUCT.md
Labels: documentation, Hacktoberfest

#17 Code base cleanup
  client/.eslintcache
  client/src/components/App.js
  client/src/components/LandingPage.css
  client/src/components/LandingPage.js
  client/src/components/SwipeTab.js
  client/src/components/YourBookmarks.js
  client/src/components/feed/Feed.css
  client/src/components/feed/Feed.js
  client/src/components/feed/FeedConfessions.css
  client/src/components/feed/FeedConfessions.js
  client/src/components/feed/FeedEvents.css
  client/src/components/feed/FeedEvents.js
  client/src/components/navigation/BottomNavigationMobile.css
  client/src/components/navigation/BottomNavigationMobile.js
  client/src/components/navigation/Sidebar.css
  client/src/components/navigation/Sidebar.js
  client/src/components/navigation/SidebarOptions.css
  client/src/components/navigation/SidebarOptions.js
  client/src/components/user/UserEvents.js
  client/src/components/user/UserPosts.js
  client/src/components/user/UserProfile.css
  client/src/components/user/UserProfile.js
  client/src/components/user/UserSwipeTab.js
  client/src/components/user/client/YourBookmarks.css
  client/src/components/user/client/YourBookmarks.js
  client/src/components/user/client/YourEvents.css
  client/src/components/user/client/YourEvents.js
  client/src/components/user/client/YourPosts.css
  client/src/components/user/client/YourPosts.js
Labels: Hacktoberfest, refactor

#16 Initial landing page
  client/src/components/LandingPage.css
  client/src/components/LandingPage.js
Labels: enhancement, Hacktoberfest

#19 docs: Added issues and pr templates in .github file
  .github/ISSUES_TEMPLATES/bug_report.md
  .github/ISSUES_TEMPLATES/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, Hacktoberfest

#23 style: search bar
  client/.eslintcache
  client/src/components/Search.js
  client/src/components/Widgets.css
Labels: enhancement, Hacktoberfest

#22 fix: issue templates not displaying
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, good first issue, Hacktoberfest
